name: Java CI

on:
  push:

jobs:
  package:
    name: MyToolbox on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '20.0.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-m2
      - name: Build Zip Package
        run: mvn clean package -Pnative
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: my-toolbox-${{ matrix.os }}.zip
          path: my-toolbox-bin.zip